Add PostgreSQL Client Support with Connection String and In-Memory Fallback
palixir/wabe pull request #97
Opened 2024-11-16 02:22 UTC by stawuah

## Overview
This PR introduces a flexible PostgreSQL client implementation that supports multiple connection methods:
- Connection string-based connections
- Default PostgreSQL configuration
- Fallback to in-memory PostgreSQL for testing and development

## Changes
- Added `WabePostgresClient` for handling PostgreSQL connections
- Implemented connection string support
- Added default PostgreSQL configuration support
- Created in-memory PostgreSQL fallback for testing
- Added comprehensive test suite
- Added `testPostgresClient` helper for testing purposes

## Testing
- Added test suite covering all connection methods
- Tested error handling and fallback scenarios
- Verified connection string parsing
- Confirmed proper port configuration handling
- Added mocking for PostgreSQL client in tests

## Type of Change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?
- Unit tests using Bun test framework
- Manual testing with actual PostgreSQL instance
- Test coverage for all connection paths
- Error handling verification

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Configuration Example
```typescript
// Connection string usage
const client = await WabePostgresClient({
  connection_string: "postgresql://user:pass@localhost:5432/db",
  options: { useConnectionString: true }
});

// Default PostgreSQL configuration
const client = await WabePostgresClient({
  db_user: "user",
  host: "localhost",
  database: "db",
  password: "pass",
  port: 5432,
  options: { useDefaultPostgres: true }
});
```

## Testing and Development Example
```typescript
// Use in-memory PostgreSQL for tests
const testClient = await testPostgresClient();
```

2024-11-16 13:37 UTC, coratgerl requested changes
Thanks for the work !

Seems a little overkill for just the job, you just need to initialize and run a db memory server. All the query part will be in wabe package in PostgresAdapter.ts

2024-11-16 13:37 UTC, coratgerl commented on packages/wabe-postgres-launcher/index.ts
> +    await client.query('SELECT NOW();')
The client should not be created here. The memory launcher should only run the database. Like on mongo launcher

2024-11-16 13:37 UTC, coratgerl commented on packages/wabe-postgres-launcher/index.ts
> +    }
This should not be here. You should initialize the database in memory here and in the PostgresAdapter in wabe package you will create pg client

2024-11-16 13:37 UTC, coratgerl commented on packages/wabe-postgres-launcher/interface/wabe-postgres-interface.ts
> +/**
Same for this, this should not be here

2024-11-16 13:37 UTC, coratgerl commented on packages/wabe-postgres-launcher/test-in-memory.utils.ts
> +/**
seems weird to have all this function.

2024-11-20 18:56 UTC, stawuah commented on packages/wabe-postgres-launcher/test-in-memory.utils.ts
> +/**
Sure thing, this would be out on the next review

2024-11-20 18:56 UTC, stawuah commented on packages/wabe-postgres-launcher/interface/wabe-postgres-interface.ts
> +/**
copy that 👌🏾

2024-11-20 19:25 UTC, stawuah commented on packages/wabe-postgres-launcher/index.ts
> +    await client.query('SELECT NOW();')
@coratgerl, I would like to outline some steps before carrying out the refactor here

- Get the `WabeInMemoryPostgres` simplified to only launch the database
- Remove client creation logic
- Add static launch() method to init db
- Keep minimal logging and error handling

2024-11-20 19:30 UTC, stawuah commented on packages/wabe-postgres-launcher/index.ts
> +    }
Also in this section, a few steps to tackle the refactor 

- I will remove direct client creation
- Create a utility to resolve connection parameters
- Returns either a connection string or connection configuration
- Allow the PostgresAdapter to handle actual client creation

2024-11-20 19:32 UTC, stawuah commented on packages/wabe-postgres-launcher/index.ts
> +    }
@coratgerl, I will require feedback or enough clarity so I commence with the refactor 🙏

2024-11-21 07:29 UTC, coratgerl commented on packages/wabe-postgres-launcher/index.ts
> +    await client.query('SELECT NOW();')
Yes, exactly like on mongodb-launcher

2025-01-14 17:22 UTC, coratgerl commented
inactive

2025-01-14 17:22 UTC, closed without merging